# Generated by Django 4.1.5 on 2023-03-06 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monaie', models.CharField(max_length=100, null=True)),
                ('type_paiement', models.CharField(max_length=100, null=True)),
                ('taux', models.IntegerField(blank=True, default=0, null=True)),
                ('charge', models.CharField(max_length=100, null=True)),
                ('limite_retrait', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('localisation', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retrait', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant', models.FloatField(null=True)),
                ('conversion', models.CharField(max_length=100, null=True)),
                ('en_attente', models.BooleanField(blank=True, default=False, null=True)),
                ('approuves', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payfina.client')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payfina.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, null=True)),
                ('message', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payfina.client')),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='pays',
            field=models.ManyToManyField(blank=True, to='payfina.pays', verbose_name='Pays'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payfina.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Depots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depot', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant', models.FloatField(null=True)),
                ('conversion', models.CharField(max_length=100, null=True)),
                ('en_attente', models.BooleanField(blank=True, default=False, null=True)),
                ('approuves', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payfina.client')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payfina.paiement')),
            ],
        ),
    ]
